thaiscore = float(input(""))
mathscore = float(input(""))
engscore = float(input(""))
sciscore = float(input(""))
sportscore = float(input(""))
print("THAI =",thaiscore)
print("MATH =",mathscore)
print("ENGLISH =",engscore)
print("SCIENCE =",sciscore)
print("SPORT =",sportscore)
print("---")
gpa = (thaiscore+mathscore+engscore+sciscore+sportscore)/5
print("GPA =",gpa)
