num1 = int(input("Number 1 : "))
num2 = int(input("Number 2 : "))
num3 = int(input("Number 3 : "))
num4 = int(input("Number 4 : "))
num5 = int(input("Number 5 : "))
print(str(min(num1,num2,num3,num4,num5))+", "+str(max(num1,num2,num3,num4,num5)))