name = input("กรอกชื่อจริง : ")
lname = input("กรอกนามสกุล : ")
birthDay = input("กรอกวันเกิด : ")
print("#############################")
print("#  _  _ ___ _    _    ___   #")
print("# | || | __| |  | |  / _ \\  #")
print("# | __ | _|| |__| |_| (_) | #")
print("# |_||_|___|____|____\\___/  #")
print("#                           #")
print("#############################")
print("=============================")
print("My name is      "+name,lname)
print("My birthday is  "+birthDay)
print("You can call me "+name)
print("=============================")
